//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autypo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autypo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize without a data source..
        /// </summary>
        internal static string AutypoConfiguration_MissingDataSource {
            get {
                return ResourceManager.GetString("AutypoConfiguration_MissingDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to index records of type {0} without a key selector..
        /// </summary>
        internal static string AutypoConfiguration_MissingKey {
            get {
                return ResourceManager.GetString("AutypoConfiguration_MissingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Token Matching can only be used if Token Reordering is enabled.
        /// </summary>
        internal static string AutypoConfiguration_PartialMatching_ReorderingDisabled {
            get {
                return ResourceManager.GetString("AutypoConfiguration_PartialMatching_ReorderingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UninitializedBehavior must be specified for this initialization mode.
        /// </summary>
        internal static string AutypoConfiguration_UninitializationMode_Incompatible {
            get {
                return ResourceManager.GetString("AutypoConfiguration_UninitializationMode_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The engine has already been configured..
        /// </summary>
        internal static string AutypoEngine_AutypoSearch_AlreadyConfigured {
            get {
                return ResourceManager.GetString("AutypoEngine_AutypoSearch_AlreadyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The engine must first be configured..
        /// </summary>
        internal static string AutypoEngine_AutypoSearch_NotConfigured {
            get {
                return ResourceManager.GetString("AutypoEngine_AutypoSearch_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified document type does not match the autocomplete..
        /// </summary>
        internal static string AutypoQueryContext_Invalid_DocumentType {
            get {
                return ResourceManager.GetString("AutypoQueryContext_Invalid_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one AutypoCompleter matched the requested parameters.
        /// </summary>
        internal static string AutypoService_Ambiguous {
            get {
                return ResourceManager.GetString("AutypoService_Ambiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified AutypoCompleter was not found.
        /// </summary>
        internal static string AutypoService_NotFound {
            get {
                return ResourceManager.GetString("AutypoService_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source tokens must have at least one token..
        /// </summary>
        internal static string AutypoToken_SourceIsEmpty {
            get {
                return ResourceManager.GetString("AutypoToken_SourceIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to search for a value as the data has not yet been loaded..
        /// </summary>
        internal static string Search_Uninitialized {
            get {
                return ResourceManager.GetString("Search_Uninitialized", resourceCulture);
            }
        }
    }
}
